# Generated by Django 4.2.7 on 2023-12-05 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipment_groups', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoricalEquipmentGroup',
        ),
    ]
