# Generated by Django 4.2.7 on 2023-11-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('equipments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='last_changed_by',
        ),
        migrations.RemoveField(
            model_name='equipmentinstance',
            name='last_changed_by',
        ),
        migrations.RemoveField(
            model_name='historicalequipmentinstance',
            name='last_changed_by',
        ),
    ]
